FROM arm64v8/alpine:3.13.4@sha256:071fa5de01a240dbef5be09d69f8fef2f89d68445d9175393773ee389b6f5935

LABEL maintainer="David Howell <david@davidjameshowell.com>" \
  org.opencontainers.image.title="Alpine" \
  org.opencontainers.image.vendor="David Howell"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-arm64v8 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec tini s6 && \
  curl -sSLo /usr/bin/wait-for-it https://raw.githubusercontent.com/thegeeklab/wait-for/d17c23172a39d7555f184d916881aeae6d446a22/wait-for && \
  chmod +x /usr/bin/wait-for-it && \
  rm -rf /var/cache/apk/*
